#!/bin/bash

# Setup Nerd Font for proper icon display
echo "=== SETTING UP NERD FONT FOR ICONS ==="
echo ""
echo "🎯 To fix the square icons issue:"
echo ""
echo "📋 Manual Steps Required:"
echo "1. Open Terminal preferences (Terminal > Preferences)"
echo "2. Go to Profiles tab"
echo "3. Select your current profile (or create new one)"
echo "4. Go to Text tab"
echo "5. Change font to 'JetBrainsMono Nerd Font' (or any Nerd Font)"
echo "6. Set font size to 12-14pt"
echo "7. Click 'Use this font when starting new terminal sessions'"
echo "8. Restart Terminal and Neovim"
echo ""
echo "🔧 Alternative: Use iTerm2 (better font support)"
echo "• Download iTerm2 from https://iterm2.com"
echo "• Set font to 'JetBrainsMono Nerd Font'"
echo "• Much better icon rendering"
echo ""
echo "✅ After font setup, icons will display properly!"
echo ""
echo "📋 Available Nerd Fonts installed:"
ls ~/Library/Fonts/ | grep -i nerd | head -5
echo ""
echo "🎯 Recommended: JetBrainsMono Nerd Font"
echo "   - Best for coding"
echo "   - Excellent icon support"
echo "   - Great readability"
